// "Local Living" essentials for Hat Yai & Songkhla — the layer that turns a
// one-trip tourist app into a daily-use app for residents too. Curated, static
// data (same shape philosophy as landmarks.js): hospitals, pharmacies,
// transport hubs, and public services, plus a one-tap EMERGENCY list.
//
// `phone` is a dial string (used in a tel: link). `lat/lng` drive a Google Maps
// directions link via gmapsUrl() from landmarks.js. Coordinates are approximate
// (good enough to drop a pin / get directions).
import {
  Hospital,
  Stethoscope,
  Pill,
  Plane,
  TrainFront,
  Bus,
  Building2,
  Landmark,
  ShieldAlert,
  Flame,
  Ambulance,
  ShieldCheck,
  GraduationCap,
  Banknote,
} from "lucide-react";

// One-tap national emergency numbers (Thailand). Shown at the top of the
// Essentials screen and behind the big SOS button.
export const EMERGENCY = [
  { id: "medical",  phone: "1669", Icon: Ambulance,    tone: "rose",   th: "การแพทย์ฉุกเฉิน", en: "Medical / Ambulance" },
  { id: "police",   phone: "191",  Icon: ShieldAlert,  tone: "blue",   th: "ตำรวจ", en: "Police" },
  { id: "fire",     phone: "199",  Icon: Flame,        tone: "orange", th: "ดับเพลิง", en: "Fire" },
  { id: "tourist",  phone: "1155", Icon: ShieldCheck,  tone: "teal",   th: "ตำรวจท่องเที่ยว", en: "Tourist Police" },
];

// Service categories, in display order, with the icon + accent used for tabs.
export const CATEGORIES = [
  { id: "hospital",  Icon: Hospital,    th: "โรงพยาบาล", en: "Hospitals" },
  { id: "pharmacy",  Icon: Pill,        th: "ร้านยา/คลินิก", en: "Pharmacy / Clinic" },
  { id: "transport", Icon: Bus,         th: "การเดินทาง", en: "Transport" },
  { id: "service",   Icon: Landmark,    th: "บริการสาธารณะ", en: "Public services" },
  { id: "education", Icon: GraduationCap, th: "การศึกษา", en: "Education" },
];

export const ESSENTIALS = [
  // ── Healthcare ─────────────────────────────────────────────────────────
  {
    id: "psu-hospital",
    category: "hospital",
    Icon: Hospital,
    th: "โรงพยาบาลสงขลานครินทร์ (ม.อ.)",
    en: "Songklanagarind Hospital (PSU)",
    district: "หาดใหญ่",
    lat: 7.0083, lng: 100.4983,
    phone: "074455000",
    hours24: true,
    th_note: "โรงพยาบาลมหาวิทยาลัย ศูนย์การแพทย์ใหญ่ที่สุดของภาคใต้",
    en_note: "University hospital — the South's largest medical center",
  },
  {
    id: "hatyai-hospital",
    category: "hospital",
    Icon: Hospital,
    th: "โรงพยาบาลหาดใหญ่",
    en: "Hat Yai Hospital",
    district: "หาดใหญ่",
    lat: 7.0096, lng: 100.4742,
    phone: "074273100",
    hours24: true,
    th_note: "โรงพยาบาลศูนย์ประจำจังหวัด ห้องฉุกเฉิน 24 ชม.",
    en_note: "Provincial regional hospital, 24h ER",
  },
  {
    id: "bangkok-hatyai",
    category: "hospital",
    Icon: Hospital,
    th: "โรงพยาบาลกรุงเทพหาดใหญ่",
    en: "Bangkok Hospital Hat Yai",
    district: "หาดใหญ่",
    lat: 7.0181, lng: 100.4699,
    phone: "074272800",
    hours24: true,
    th_note: "โรงพยาบาลเอกชน รองรับผู้ป่วยต่างชาติ",
    en_note: "Private hospital, English-speaking, international patients",
  },
  {
    id: "songkhla-hospital",
    category: "hospital",
    Icon: Hospital,
    th: "โรงพยาบาลสงขลา",
    en: "Songkhla Hospital",
    district: "เมืองสงขลา",
    lat: 7.1899, lng: 100.5947,
    phone: "074338100",
    hours24: true,
    th_note: "โรงพยาบาลทั่วไปประจำอำเภอเมืองสงขลา",
    en_note: "General hospital in Songkhla town",
  },
  // ── Pharmacy / clinic ──────────────────────────────────────────────────
  {
    id: "fascino-hatyai",
    category: "pharmacy",
    Icon: Pill,
    th: "ร้านยาฟาสซิโน หาดใหญ่",
    en: "Fascino Pharmacy (Hat Yai)",
    district: "หาดใหญ่",
    lat: 7.0086, lng: 100.4744,
    th_note: "เครือร้านยามาตรฐาน มีหลายสาขาในเมือง",
    en_note: "Trusted pharmacy chain, several branches downtown",
  },
  {
    id: "watson-central",
    category: "pharmacy",
    Icon: Stethoscope,
    th: "วัตสัน เซ็นทรัลหาดใหญ่",
    en: "Watsons (Central Hat Yai)",
    district: "หาดใหญ่",
    lat: 7.0246, lng: 100.4682,
    th_note: "ร้านยา-สุขภาพในห้าง เปิดตามเวลาห้าง",
    en_note: "Pharmacy & health in the mall (mall hours)",
  },
  // ── Transport ──────────────────────────────────────────────────────────
  {
    id: "hatyai-airport",
    category: "transport",
    Icon: Plane,
    th: "ท่าอากาศยานนานาชาติหาดใหญ่",
    en: "Hat Yai International Airport",
    district: "คลองหอยโข่ง",
    lat: 6.9333, lng: 100.3925,
    phone: "074227000",
    th_note: "สนามบินหลักภาคใต้ตอนล่าง ห่างตัวเมือง ~12 กม.",
    en_note: "Main southern airport, ~12 km from downtown",
  },
  {
    id: "hatyai-junction",
    category: "transport",
    Icon: TrainFront,
    th: "สถานีรถไฟชุมทางหาดใหญ่",
    en: "Hat Yai Junction Railway Station",
    district: "หาดใหญ่",
    lat: 7.0039, lng: 100.4676,
    phone: "1690",
    th_note: "ชุมทางรถไฟสายใต้ ไป กทม./ปาดังเบซาร์",
    en_note: "Southern-line junction to Bangkok / Padang Besar",
  },
  {
    id: "hatyai-bus-terminal",
    category: "transport",
    Icon: Bus,
    th: "สถานีขนส่งหาดใหญ่ (บขส.)",
    en: "Hat Yai Bus Terminal (BKS)",
    district: "หาดใหญ่",
    lat: 7.0046, lng: 100.4869,
    th_note: "รถทัวร์–รถตู้ระหว่างจังหวัดและข้ามแดน",
    en_note: "Inter-province & cross-border coaches and vans",
  },
  {
    id: "songthaew-info",
    category: "transport",
    Icon: Bus,
    th: "รถสองแถวในเมืองหาดใหญ่",
    en: "Hat Yai Songthaew (shared pickup)",
    district: "หาดใหญ่",
    lat: 7.0086, lng: 100.4747,
    th_note: "รถแดง/รถตามสี วิ่งเส้นหลักทั่วเมือง เริ่ม ~10 บาท ทักคนขับเพื่อลง",
    en_note: "Color-coded shared pickups on main routes, from ~฿10; wave to stop",
  },
  {
    id: "koyo-ferry",
    category: "transport",
    Icon: Bus,
    th: "ทางขึ้นเกาะยอ (สะพานติณฯ)",
    en: "Ko Yo access (Tinsulanonda Bridge)",
    district: "เกาะยอ",
    lat: 7.1644, lng: 100.5447,
    th_note: "ข้ามสะพานติณสูลานนท์สู่เกาะยอ ของกิน-ผ้าทอ",
    en_note: "Cross Tinsulanonda Bridge to Ko Yo (food & weaving)",
  },
  // ── Public services ────────────────────────────────────────────────────
  {
    id: "hatyai-municipality",
    category: "service",
    Icon: Building2,
    th: "เทศบาลนครหาดใหญ่",
    en: "Hat Yai City Municipality",
    district: "หาดใหญ่",
    lat: 7.0094, lng: 100.4744,
    phone: "074200000",
    th_note: "งานทะเบียน บริการประชาชน ข้อมูลเมือง",
    en_note: "City services, registration, local info",
  },
  {
    id: "immigration-songkhla",
    category: "service",
    Icon: ShieldCheck,
    th: "ตรวจคนเข้าเมืองสงขลา (หาดใหญ่)",
    en: "Songkhla Immigration (Hat Yai)",
    district: "หาดใหญ่",
    lat: 7.0176, lng: 100.4675,
    phone: "074257019",
    th_note: "ต่อวีซ่า รายงานตัว 90 วัน บริการชาวต่างชาติ",
    en_note: "Visa extension, 90-day report, foreigner services",
  },
  {
    id: "malaysia-consulate",
    category: "service",
    Icon: Landmark,
    th: "สถานกงสุลมาเลเซีย สงขลา",
    en: "Consulate of Malaysia, Songkhla",
    district: "เมืองสงขลา",
    lat: 7.2030, lng: 100.5950,
    th_note: "บริการกงสุลสำหรับนักเดินทางข้ามแดนไทย-มาเลเซีย",
    en_note: "Consular services for Thai–Malaysia cross-border travel",
  },
  {
    id: "tourist-police-booth",
    category: "service",
    Icon: ShieldCheck,
    th: "ตำรวจท่องเที่ยวหาดใหญ่",
    en: "Tourist Police, Hat Yai",
    district: "หาดใหญ่",
    lat: 7.0089, lng: 100.4759,
    phone: "1155",
    th_note: "ช่วยเหลือนักท่องเที่ยว แจ้งเหตุ ภาษาอังกฤษ",
    en_note: "Help & reporting for tourists, English-speaking",
  },
  {
    id: "bank-atm-strip",
    category: "service",
    Icon: Banknote,
    th: "ธนาคาร/ตู้ ATM ถนนเสน่หานุสรณ์",
    en: "Banks / ATMs (Sanehanusorn Rd)",
    district: "หาดใหญ่",
    lat: 7.0084, lng: 100.4731,
    th_note: "ย่านธนาคารและแลกเงินใจกลางเมืองหาดใหญ่",
    en_note: "Bank & currency-exchange strip in central Hat Yai",
  },
  // ── Education ──────────────────────────────────────────────────────────
  {
    id: "psu-university",
    category: "education",
    Icon: GraduationCap,
    th: "มหาวิทยาลัยสงขลานครินทร์ (ม.อ.หาดใหญ่)",
    en: "Prince of Songkla University (PSU)",
    district: "หาดใหญ่",
    lat: 7.0061, lng: 100.4986,
    th_note: "มหาวิทยาลัยหลักของภาคใต้ วิทยาเขตหาดใหญ่",
    en_note: "The South's flagship university, Hat Yai campus",
  },
  {
    id: "tsu-university",
    category: "education",
    Icon: GraduationCap,
    th: "มหาวิทยาลัยทักษิณ (สงขลา)",
    en: "Thaksin University, Songkhla",
    district: "เมืองสงขลา",
    lat: 7.1556, lng: 100.6133,
    th_note: "วิทยาเขตสงขลา ริมทะเลสาบ",
    en_note: "Songkhla campus by the lagoon",
  },
];

// Tone -> Tailwind classes for emergency cards / category accents.
export const TONES = {
  rose:   { text: "text-rose-600 dark:text-rose-300",   bg: "bg-rose-500/15",   ring: "border-rose-500/30" },
  blue:   { text: "text-blue-600 dark:text-blue-300",   bg: "bg-blue-500/15",   ring: "border-blue-500/30" },
  orange: { text: "text-orange-600 dark:text-orange-300", bg: "bg-orange-500/15", ring: "border-orange-500/30" },
  teal:   { text: "text-lagoon",                         bg: "bg-lagoon/15",     ring: "border-lagoon/30" },
};

export function essentialsByCategory(category) {
  return ESSENTIALS.filter((e) => e.category === category);
}
